name: cache fixture smoke test

on:
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  build:
    uses: cheirekov/nix-aws-build-infra/.github/workflows/nix-build.yml@main
    with:
      flake_attribute: checks.x86_64-linux.fixture
      timeout_minutes: 30
